import type { Metadata } from 'next';

import { Header } from '@/components';
import { marianne, spectral } from '@/styles/fonts';
import { initDsfr } from '@/utils/dsfr';

// DSFR initialization
initDsfr();

export const metadata: Metadata = {
  title: 'Mon Devis Sans Oublis',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${marianne.variable} ${spectral.variable}`}
      data-fr-scheme='system'
      lang='fr'
    >
      <head>
        <meta
          content='telephone=no,date=no,address=no,email=no,url=no'
          name='format-detection'
        />
        <meta
          content='width=device-width, initial-scale=1, shrink-to-fit=no'
          name='viewport'
        />
        <meta content='#000091' name='theme-color' />
        <link
          href='/dsfr/favicon/apple-touch-icon.png'
          rel='apple-touch-icon'
        />
        <link
          href='/dsfr/favicon/favicon.svg'
          rel='icon'
          type='image/svg+xml'
        />
        <link
          href='/dsfr/favicon/favicon.ico'
          rel='shortcut icon'
          type='image/x-icon'
        />
        <link
          crossOrigin='use-credentials'
          href='/dsfr/favicon/manifest.webmanifest'
          rel='manifest'
        />
      </head>
      <body>
        <Header
          affiliatedMinistry={['Ministère', 'de la transition', 'écologique']}
          buttons={[
            {
              href: 'https://mon-devis-sans-oublis.beta.gouv.fr/contact',
              icon: 'question-line',
              label: 'Nous contacter',
            },
          ]}
          organizationDetails='Vérifiez vos devis de rénovation énergétique'
          organizationLink='https://mon-devis-sans-oublis.beta.gouv.fr/'
          organizationName='Mon Devis Sans Oublis'
        />
        {children}
      </body>
    </html>
  );
}
